### ISSUE TITLE
Introduce Yourselves

### ISSUE THREAD

**Issue by gaurav1999** [gaurav1999/LearnGit#1]
Hi,
Participants need to introduce themselves. For instructions on introduction and raising a PR follow the README.md .

We want to put a slight learning curve here and to let you learn your first experience with Upstream repositories.
In order to filter out serious participants we have came up with this solution, I hope you will be able to manage it.

**Comment by Gargi-Jaiswal** [comment]
gargi.md

**Comment by Gargi-Jaiswal** [comment]
gargi.md

**Comment by Gargi-Jaiswal** [comment]
[gargi.md](url)

**Comment by gaurav1999** [comment]
It's solved now, we are no more taking any participants. Thanks all of the guys for working on their PR's
